### ISSUE TITLE
Playbook Generator only accepts one configmap 

### ISSUE THREAD

**Issue by snecklifter** [openstack-k8s-operators/osp-director-operator#244]
In testing it seems that two configmaps tarballs are not accepted, e.g.

```
oc create configmap -n openstack tripleo-net-config --from-file=net-config.tar.gz
oc create configmap -n openstack tripleo-deploy-config-custom --from-file=tripleo-deploy-config-custom.tar.gz
```

**Comment by dprince** [comment]
This is correct. When we implemented the OpenStackPlaybook generator we simplified the configmaps into two types. One ConfigMap is use for custom Heat ENV files. These are ordered and applied in order during playbook generation.

The second configmap is a tarball configmap used to extract generic heat templates into your t-h-t root before playbooks are generated. These can be any type of templates including network configuration (which is really just a special case we implemented before as we didn't support tarballs). As such we just dropped the special case tripleo-net-config since it is no longer needed.

So something like this should work now:

     tar -cvzf net-config.tar.gz *.yaml
     oc create configmap -n openstack tripleo-net-config --from-file=net-config.tar.gz

Note: this tarball config map can be named whatever you want, and can contain multiple tarballs.

**Comment by snecklifter** [comment]
> As such we just dropped the special case tripleo-net-config since it is no longer needed.

Ok but then your example includes this?

` oc create configmap -n openstack tripleo-net-config --from-file=net-config.tar.gz`

**Comment by snecklifter** [comment]
> So we replaced the special case 'net-config' map with a generic tarball config map. But I left the name of the config map the same so I can understand how that is confusing.
> 
> Perhaps I should rename that config map to tripleo-template-tarballs to clarify this explicitly. We'll still use it to inject the custom network templates I think its just the naming that is causing confusion?

Yes and I suppose how the playbook generator knows which configmap to use. Does it need to start tripleo- for example?

**Comment by dprince** [comment]
You specify it directly on the CR for osplaybook generator :)

apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackPlaybookGenerator
metadata:
  name: default
  namespace: openstack
spec:
  gitSecret: git-secret
  imageURL: quay.io/openstack-k8s-operators/tripleo-deploy:16.2_20210309.1
  heatEnvConfigMap: tripleo-deploy-config-custom
  tarballConfigMap: tripleo-net-config
